<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asset extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Asset_model');
    } 

    /*
     * Listing of asset
     */
    function index()
    {/*
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('asset/index?');
        $config['total_rows'] = $this->Asset_model->get_all_asset_count();
        $this->pagination->initialize($config);

        $data['asset'] = $this->Asset_model->get_all_asset($params);
		*/
		$data['asset'] = $this->Asset_model->get_all_asset();
        $data['_view'] = 'asset/index';
        $this->load->view('test',$data);
	}
	
	function index2()
    {
        $data['asset'] = $this->Asset_model->get_all_asset();
        $data['_view'] = 'item_table/demo';
        $this->load->view('test',$data);
	}
	
	function index3()
    {
        $data['asset'] = $this->Asset_model->get_all_asset();
        $data['_view'] = 'sync';
        $this->load->view('test',$data);
	}
	
	function index4()
    {
        $data['asset'] = $this->Asset_model->get_all_asset();
        //$data['_view'] = 'item_table/test_export';
		$this->load->view('item_table/test_export',$data);
		//$this->load->view('test',$data);
		//$this->load->view('item_table/test_export');
	}
	
	function index5()
    {
        $data['asset'] = $this->Asset_model->get_all_asset();
        //$data['_view'] = 'item_table/test_export1';
        $this->load->view('item_table/test_export1',$data);
	}

	function index6()
    {
        $data['asset'] = $this->Asset_model->get_all_asset();
        //$data['_view'] = 'item_table/function_export';
        $this->load->view('item_table/function_export',$data);
	}

	function index7()
    {
        $data['asset'] = $this->Asset_model->get_all_asset();
        //$data['_view'] = 'item_table/exporter';
        $this->load->view('item_table/exporter',$data);
	}

    /*
     * Adding a new asset
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
			$odate=date("y-m-d");
            $params = array(
				'ASSETID' => $this->input->post('ASSETID'),
				'REFERID' => $this->input->post('REFERID'),
				'ASSETNAME' => $this->input->post('ASSETNAME'),
				'RECEIVEDATE' => $odate,
				'SPEC' => $this->input->post('SPEC'),
				'UNITNAME' => $this->input->post('UNITNAME'),
            );
            
            $asset_id = $this->Asset_model->add_asset($params);
            redirect('asset/index');
        }
        else
        {
			$this->load->model('Refer_model');
			$data['all_refer'] = $this->Refer_model->get_all_refer();
            
            $data['_view'] = 'asset/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a asset
     */
    function edit($ASSETID)
    {   
        // check if the asset exists before trying to edit it
        $data['asset'] = $this->Asset_model->get_asset($ASSETID);
        
        if(isset($data['asset']['ASSETID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
				$odate=date("y-m-d");
                $params = array(
					'ASSETID' => $this->input->post('ASSETID'),
					'REFERID' => $this->input->post('REFERID'),
					'ASSETNAME' => $this->input->post('ASSETNAME'),
					'RECEIVEDATE' => $odate,
					'SPEC' => $this->input->post('SPEC'),
					'UNITNAME' => $this->input->post('UNITNAME'),
                );

                $this->Asset_model->update_asset($ASSETID,$params);            
                redirect('asset/index');
            }
            else
            {
				$this->load->model('Refer_model');
				$data['all_refer'] = $this->Refer_model->get_all_refer();

                $data['_view'] = 'asset/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The asset you are trying to edit does not exist.');
    } 

    /*
     * Deleting asset
     */
    function remove($ASSETID)
    {
        $asset = $this->Asset_model->get_asset($ASSETID);

        // check if the asset exists before trying to delete it
        if(isset($asset['ASSETID']))
        {
            $this->Asset_model->delete_asset($ASSETID);
            redirect('asset/index');
        }
        else
            show_error('The asset you are trying to delete does not exist.');
    }
    
}
