<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Building_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Building_table_model');
    } 

    /*
     * Listing of building_table
     */
    function index()
    {
        $data['building_table'] = $this->Building_table_model->get_all_building_table();
        
        $data['_view'] = 'building_table/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new building_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'BUILDING_LAT' => $this->input->post('BUILDING_LAT'),
				'BUILDING_LONG' => $this->input->post('BUILDING_LONG'),
				'BUILDING_NAME' => $this->input->post('BUILDING_NAME'),
            );
            
            $building_table_id = $this->Building_table_model->add_building_table($params);
            redirect('building_table/index');
        }
        else
        {            
            $data['_view'] = 'building_table/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a building_table
     */
    function edit($BUILDING_RID)
    {   
        // check if the building_table exists before trying to edit it
        $data['building_table'] = $this->Building_table_model->get_building_table($BUILDING_RID);
        
        if(isset($data['building_table']['BUILDING_RID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'BUILDING_LAT' => $this->input->post('BUILDING_LAT'),
					'BUILDING_LONG' => $this->input->post('BUILDING_LONG'),
					'BUILDING_NAME' => $this->input->post('BUILDING_NAME'),
                );

                $this->Building_table_model->update_building_table($BUILDING_RID,$params);            
                redirect('building_table/index');
            }
            else
            {
                $data['_view'] = 'building_table/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The building_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting building_table
     */
    function remove($BUILDING_RID)
    {
        $building_table = $this->Building_table_model->get_building_table($BUILDING_RID);

        // check if the building_table exists before trying to delete it
        if(isset($building_table['BUILDING_RID']))
        {
            $this->Building_table_model->delete_building_table($BUILDING_RID);
            redirect('building_table/index');
        }
        else
            show_error('The building_table you are trying to delete does not exist.');
    }
    
}
