<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Floor_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Floor_table_model');
    } 

    /*
     * Listing of floor_table
     */
    function index()
    {
        $data['floor_table'] = $this->Floor_table_model->get_all_floor_table();
        
        $data['_view'] = 'floor_table/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new floor_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'floor_number' => $this->input->post('floor_number'),
				'building_rid' => $this->input->post('building_rid'),
            );
            
            $floor_table_id = $this->Floor_table_model->add_floor_table($params);
            redirect('floor_table/index');
        }
        else
        {            
            $data['_view'] = 'floor_table/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a floor_table
     */
    function edit($floor_rid)
    {   
        // check if the floor_table exists before trying to edit it
        $data['floor_table'] = $this->Floor_table_model->get_floor_table($floor_rid);
        
        if(isset($data['floor_table']['floor_rid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'floor_number' => $this->input->post('floor_number'),
					'building_rid' => $this->input->post('building_rid'),
                );

                $this->Floor_table_model->update_floor_table($floor_rid,$params);            
                redirect('floor_table/index');
            }
            else
            {
                $data['_view'] = 'floor_table/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The floor_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting floor_table
     */
    function remove($floor_rid)
    {
        $floor_table = $this->Floor_table_model->get_floor_table($floor_rid);

        // check if the floor_table exists before trying to delete it
        if(isset($floor_table['floor_rid']))
        {
            $this->Floor_table_model->delete_floor_table($floor_rid);
            redirect('floor_table/index');
        }
        else
            show_error('The floor_table you are trying to delete does not exist.');
    }
    
}
