<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class History_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('History_table_model');
    } 

    /*
     * Listing of history_table
     */
    function index()
    {
        $data['history_table'] = $this->History_table_model->get_all_history_table();
        
        $data['_view'] = 'history_table/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new history_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'history_owner_uid' => $this->input->post('history_owner_uid'),
				'history_building_lat' => $this->input->post('history_building_lat'),
				'history_building_long' => $this->input->post('history_building_long'),
				'history_floor' => $this->input->post('history_floor'),
				'history_room' => $this->input->post('history_room'),
				'history_hour' => $this->input->post('history_hour'),
				'history_minute' => $this->input->post('history_minute'),
				'history_day' => $this->input->post('history_day'),
				'history_month' => $this->input->post('history_month'),
				'history_year' => $this->input->post('history_year'),
				'history_pos_x' => $this->input->post('history_pos_x'),
				'history_pos_y' => $this->input->post('history_pos_y'),
				'map_rid' => $this->input->post('map_rid'),
				'history_item_uid' => $this->input->post('history_item_uid'),
				'history_status_name' => $this->input->post('history_status_name'),
				'history_building_name' => $this->input->post('history_building_name'),
            );
            
            $history_table_id = $this->History_table_model->add_history_table($params);
            redirect('history_table/index');
        }
        else
        {            
            $data['_view'] = 'history_table/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a history_table
     */
    function edit($history_rid)
    {   
        // check if the history_table exists before trying to edit it
        $data['history_table'] = $this->History_table_model->get_history_table($history_rid);
        
        if(isset($data['history_table']['history_rid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'history_owner_uid' => $this->input->post('history_owner_uid'),
				'history_building_lat' => $this->input->post('history_building_lat'),
				'history_building_long' => $this->input->post('history_building_long'),
				'history_floor' => $this->input->post('history_floor'),
				'history_room' => $this->input->post('history_room'),
				'history_hour' => $this->input->post('history_hour'),
				'history_minute' => $this->input->post('history_minute'),
				'history_day' => $this->input->post('history_day'),
				'history_month' => $this->input->post('history_month'),
				'history_year' => $this->input->post('history_year'),
				'history_pos_x' => $this->input->post('history_pos_x'),
				'history_pos_y' => $this->input->post('history_pos_y'),
				'map_rid' => $this->input->post('map_rid'),
				'history_item_uid' => $this->input->post('history_item_uid'),
				'history_status_name' => $this->input->post('history_status_name'),
				'history_building_name' => $this->input->post('history_building_name'),
                );

                $this->History_table_model->update_history_table($HISTORY_RID,$params);            
                redirect('history_table/index');
            }
            else
            {
                $data['_view'] = 'history_table/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The history_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting history_table
     */
    function remove($history_rid)
    {
        $history_table = $this->History_table_model->get_history_table($history_rid);

        // check if the history_table exists before trying to delete it
        if(isset($history_table['history_rid']))
        {
            $this->History_table_model->delete_history_table($history_rid);
            redirect('history_table/index');
        }
        else
            show_error('The history_table you are trying to delete does not exist.');
    }
    
}
