<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class History_asset_recent extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('History_asset_recent_model');
    } 

    /*
     * Listing of history_asset_recent
     */
    function index()
    {
        $data['history_asset_recent'] = $this->History_asset_recent_model->get_all_history_asset_recent();
        
        $data['_view'] = 'history_asset_recent/index';
        $this->load->view('test',$data);
	}
	
	function index1()
    {
        $data['history_asset_recent'] = $this->History_asset_recent_model->get_all_history_asset_recent();
        //$data['_view'] = 'item_table/exporter';
        $this->load->view('history_asset_recent/export_history',$data);
	}

	function index2()
    {
        $data['history_asset_recent'] = $this->History_asset_recent_model->get_all_history_asset_recent();
        //$data['_view'] = 'item_table/exporter';
        $this->load->view('history_asset_recent/imgAsset',$data);
	}

    /*
     * Adding a new history_asset_recent
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'HISTORY_REFERID' => $this->input->post('HISTORY_REFERID'),
				'HISTORY_BUILDING_ID' => $this->input->post('HISTORY_BUILDING_ID'),
				'HISTORY_FLOOR_ID' => $this->input->post('HISTORY_FLOOR_ID'),
				'HISTORY_DAY' => $this->input->post('HISTORY_DAY'),
				'HISTORY_MONTH' => $this->input->post('HISTORY_MONTH'),
				'HISTORY_YEAR' => $this->input->post('HISTORY_YEAR'),
				'HISTORY_HOUR' => $this->input->post('HISTORY_HOUR'),
				'HISTORY_MINUTE' => $this->input->post('HISTORY_MINUTE'),
				'HISTORY_ASSET_NAME' => $this->input->post('HISTORY_ASSET_NAME'),
				'HISTORY_RECEIVEDATE' => $this->input->post('HISTORY_RECEIVEDATE'),
				'HISTORY_SPEC' => $this->input->post('HISTORY_SPEC'),
				'HISTORY_UNITNAME' => $this->input->post('HISTORY_UNITNAME'),
				'HISTORY_STATUS_NAME' => $this->input->post('HISTORY_STATUS_NAME'),
				'HISTORY_REFERNAME' => $this->input->post('HISTORY_REFERNAME'),
				'HISTORY_BUILDING_NAME' => $this->input->post('HISTORY_BUILDING_NAME'),
				'HISTORY_ROOM_ID' => $this->input->post('HISTORY_ROOM_ID'),
				'HISTORY_USERNAME' => $this->input->post('HISTORY_USERNAME'),
				'HISTORY_NOTE' => $this->input->post('HISTORY_NOTE'),
            );
            
            $history_asset_recent_id = $this->History_asset_recent_model->add_history_asset_recent($params);
            redirect('history_asset_recent/index');
        }
        else
        {            
            $data['_view'] = 'history_asset_recent/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a history_asset_recent
     */
    function edit($HISTORY_ASSETID)
    {   
        // check if the history_asset_recent exists before trying to edit it
        $data['history_asset_recent'] = $this->History_asset_recent_model->get_history_asset_recent($HISTORY_ASSETID);
        
        if(isset($data['history_asset_recent']['HISTORY_ASSETID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'HISTORY_REFERID' => $this->input->post('HISTORY_REFERID'),
					'HISTORY_BUILDING_ID' => $this->input->post('HISTORY_BUILDING_ID'),
					'HISTORY_FLOOR_ID' => $this->input->post('HISTORY_FLOOR_ID'),
					'HISTORY_DAY' => $this->input->post('HISTORY_DAY'),
					'HISTORY_MONTH' => $this->input->post('HISTORY_MONTH'),
					'HISTORY_YEAR' => $this->input->post('HISTORY_YEAR'),
					'HISTORY_HOUR' => $this->input->post('HISTORY_HOUR'),
					'HISTORY_MINUTE' => $this->input->post('HISTORY_MINUTE'),
					'HISTORY_ASSET_NAME' => $this->input->post('HISTORY_ASSET_NAME'),
					'HISTORY_RECEIVEDATE' => $this->input->post('HISTORY_RECEIVEDATE'),
					'HISTORY_SPEC' => $this->input->post('HISTORY_SPEC'),
					'HISTORY_UNITNAME' => $this->input->post('HISTORY_UNITNAME'),
					'HISTORY_STATUS_NAME' => $this->input->post('HISTORY_STATUS_NAME'),
					'HISTORY_REFERNAME' => $this->input->post('HISTORY_REFERNAME'),
					'HISTORY_BUILDING_NAME' => $this->input->post('HISTORY_BUILDING_NAME'),
					'HISTORY_ROOM_ID' => $this->input->post('HISTORY_ROOM_ID'),
					'HISTORY_USERNAME' => $this->input->post('HISTORY_USERNAME'),
					'HISTORY_NOTE' => $this->input->post('HISTORY_NOTE'),
                );

                $this->History_asset_recent_model->update_history_asset_recent($HISTORY_ASSETID,$params);            
                redirect('history_asset_recent/index');
            }
            else
            {
                $data['_view'] = 'history_asset_recent/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The history_asset_recent you are trying to edit does not exist.');
    } 

    /*
     * Deleting history_asset_recent
     */
    function remove($HISTORY_ASSETID)
    {
        $history_asset_recent = $this->History_asset_recent_model->get_history_asset_recent($HISTORY_ASSETID);

        // check if the history_asset_recent exists before trying to delete it
        if(isset($history_asset_recent['HISTORY_ASSETID']))
        {
            $this->History_asset_recent_model->delete_history_asset_recent($HISTORY_ASSETID);
            redirect('history_asset_recent/index');
        }
        else
            show_error('The history_asset_recent you are trying to delete does not exist.');
    }
    
}
