<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class History_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('History_table_model');
    } 

    /*
     * Listing of history_table
     */
    function index()
    {
        $data['history_table'] = $this->History_table_model->get_all_history_table();
        
        $data['_view'] = 'history_table/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new history_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'HISTORY_OWNER_UID' => $this->input->post('HISTORY_OWNER_UID'),
				'HISTORY_BUILDING_LAT' => $this->input->post('HISTORY_BUILDING_LAT'),
				'HISTORY_BUILDING_LONG' => $this->input->post('HISTORY_BUILDING_LONG'),
				'HISTORY_FLOOR' => $this->input->post('HISTORY_FLOOR'),
				'HISTORY_ROOM' => $this->input->post('HISTORY_ROOM'),
				'HISTORY_HOUR' => $this->input->post('HISTORY_HOUR'),
				'HISTORY_MINUTE' => $this->input->post('HISTORY_MINUTE'),
				'HISTORY_DAY' => $this->input->post('HISTORY_DAY'),
				'HISTORY_MONTH' => $this->input->post('HISTORY_MONTH'),
				'HISTORY_YEAR' => $this->input->post('HISTORY_YEAR'),
				'HISTORY_POS_X' => $this->input->post('HISTORY_POS_X'),
				'HISTORY_POS_Y' => $this->input->post('HISTORY_POS_Y'),
				'MAP_RID' => $this->input->post('MAP_RID'),
				'HISTORY_ITEM_UID' => $this->input->post('HISTORY_ITEM_UID'),
				'HISTORY_STATUS_NAME' => $this->input->post('HISTORY_STATUS_NAME'),
				'HISTORY_BUILDING_NAME' => $this->input->post('HISTORY_BUILDING_NAME'),
            );
            
            $history_table_id = $this->History_table_model->add_history_table($params);
            redirect('history_table/index');
        }
        else
        {            
            $data['_view'] = 'history_table/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a history_table
     */
    function edit($HISTORY_RID)
    {   
        // check if the history_table exists before trying to edit it
        $data['history_table'] = $this->History_table_model->get_history_table($HISTORY_RID);
        
        if(isset($data['history_table']['HISTORY_RID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'HISTORY_OWNER_UID' => $this->input->post('HISTORY_OWNER_UID'),
					'HISTORY_BUILDING_LAT' => $this->input->post('HISTORY_BUILDING_LAT'),
					'HISTORY_BUILDING_LONG' => $this->input->post('HISTORY_BUILDING_LONG'),
					'HISTORY_FLOOR' => $this->input->post('HISTORY_FLOOR'),
					'HISTORY_ROOM' => $this->input->post('HISTORY_ROOM'),
					'HISTORY_HOUR' => $this->input->post('HISTORY_HOUR'),
					'HISTORY_MINUTE' => $this->input->post('HISTORY_MINUTE'),
					'HISTORY_DAY' => $this->input->post('HISTORY_DAY'),
					'HISTORY_MONTH' => $this->input->post('HISTORY_MONTH'),
					'HISTORY_YEAR' => $this->input->post('HISTORY_YEAR'),
					'HISTORY_POS_X' => $this->input->post('HISTORY_POS_X'),
					'HISTORY_POS_Y' => $this->input->post('HISTORY_POS_Y'),
					'MAP_RID' => $this->input->post('MAP_RID'),
					'HISTORY_ITEM_UID' => $this->input->post('HISTORY_ITEM_UID'),
					'HISTORY_STATUS_NAME' => $this->input->post('HISTORY_STATUS_NAME'),
					'HISTORY_BUILDING_NAME' => $this->input->post('HISTORY_BUILDING_NAME'),
                );

                $this->History_table_model->update_history_table($HISTORY_RID,$params);            
                redirect('history_table/index');
            }
            else
            {
                $data['_view'] = 'history_table/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The history_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting history_table
     */
    function remove($HISTORY_RID)
    {
        $history_table = $this->History_table_model->get_history_table($HISTORY_RID);

        // check if the history_table exists before trying to delete it
        if(isset($history_table['HISTORY_RID']))
        {
            $this->History_table_model->delete_history_table($HISTORY_RID);
            redirect('history_table/index');
        }
        else
            show_error('The history_table you are trying to delete does not exist.');
    }
    
}
