<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class History extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('History_model');
    } 

    /*
     * Listing of history
     */
    function index()
    {
        $data['history'] = $this->History_model->get_all_history();
        
        $data['_view'] = 'history/index';
        $this->load->view('test',$data);
	}
	
	function index1()
    {
        $data['history'] = $this->History_model->get_all_history();
        //$data['_view'] = 'item_table/exporter';
        $this->load->view('history/export_history',$data);
	}

    /*
     * Adding a new history
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'HISTORY_ASSETID' => $this->input->post('HISTORY_ASSETID'),
				'HISTORY_ASSET_NAME' => $this->input->post('HISTORY_ASSET_NAME'),
				'HISTORY_RECEIVEDATE' => $this->input->post('HISTORY_RECEIVEDATE'),
				'HISTORY_SPEC' => $this->input->post('HISTORY_SPEC'),
				'HISTORY_UNITNAME' => $this->input->post('HISTORY_UNITNAME'),
				'HISTORY_STATUS_NAME' => $this->input->post('HISTORY_STATUS_NAME'),
				'HISTORY_REFERID' => $this->input->post('HISTORY_REFERID'),
				'HISTORY_REFERNAME' => $this->input->post('HISTORY_REFERNAME'),
				'HISTORY_BUILDING_ID' => $this->input->post('HISTORY_BUILDING_ID'),
				'HISTORY_BUILDING_NAME' => $this->input->post('HISTORY_BUILDING_NAME'),
				'HISTORY_FLOOR_ID' => $this->input->post('HISTORY_FLOOR_ID'),
				'HISTORY_ROOM_ID' => $this->input->post('HISTORY_ROOM_ID'),
				'HISTORY_DAY' => $this->input->post('HISTORY_DAY'),
				'HISTORY_MONTH' => $this->input->post('HISTORY_MONTH'),
				'HISTORY_YEAR' => $this->input->post('HISTORY_YEAR'),
				'HISTORY_HOUR' => $this->input->post('HISTORY_HOUR'),
				'HISTORYMINUTE' => $this->input->post('HISTORYMINUTE'),
				'HISTORY_USERNAME' => $this->input->post('HISTORY_USERNAME'),
            );
            
            $history_id = $this->History_model->add_history($params);
            redirect('history/index');
        }
        else
        {            
            $data['_view'] = 'history/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a history
     */
    function edit($HISTORY_RID)
    {   
        // check if the history exists before trying to edit it
        $data['history'] = $this->History_model->get_history($HISTORY_RID);
        
        if(isset($data['history']['HISTORY_RID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'HISTORY_ASSETID' => $this->input->post('HISTORY_ASSETID'),
					'HISTORY_ASSET_NAME' => $this->input->post('HISTORY_ASSET_NAME'),
				    'HISTORY_RECEIVEDATE' => $this->input->post('HISTORY_RECEIVEDATE'),
				    'HISTORY_SPEC' => $this->input->post('HISTORY_SPEC'),
				    'HISTORY_UNITNAME' => $this->input->post('HISTORY_UNITNAME'),
					'HISTORY_STATUS_NAME' => $this->input->post('HISTORY_STATUS_NAME'),
				    'HISTORY_REFERID' => $this->input->post('HISTORY_REFERID'),
				    'HISTORY_REFERNAME' => $this->input->post('HISTORY_REFERNAME'),
				    'HISTORY_BUILDING_ID' => $this->input->post('HISTORY_BUILDING_ID'),
				    'HISTORY_BUILDING_NAME' => $this->input->post('HISTORY_BUILDING_NAME'),
					'HISTORY_FLOOR_ID' => $this->input->post('HISTORY_FLOOR_ID'),
					'HISTORY_ROOM_ID' => $this->input->post('HISTORY_ROOM_ID'),
					'HISTORY_DAY' => $this->input->post('HISTORY_DAY'),
					'HISTORY_MONTH' => $this->input->post('HISTORY_MONTH'),
					'HISTORY_YEAR' => $this->input->post('HISTORY_YEAR'),
					'HISTORY_HOUR' => $this->input->post('HISTORY_HOUR'),
					'HISTORYMINUTE' => $this->input->post('HISTORYMINUTE'),
					'HISTORY_USERNAME' => $this->input->post('HISTORY_USERNAME'),
                );

                $this->History_model->update_history($HISTORY_RID,$params);            
                redirect('history/index');
            }
            else
            {
                $data['_view'] = 'history/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The history you are trying to edit does not exist.');
    } 

    /*
     * Deleting history
     */
    function remove($HISTORY_RID)
    {
        $history = $this->History_model->get_history($HISTORY_RID);

        // check if the history exists before trying to delete it
        if(isset($history['HISTORY_RID']))
        {
            $this->History_model->delete_history($HISTORY_RID);
            redirect('history/index');
        }
        else
            show_error('The history you are trying to delete does not exist.');
    }
    
}
