<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Item_table_model');
    } 

    /*
     * Listing of item_table
     */
    function index()
    {
        $data['item_table'] = $this->Item_table_model->get_all_item_table();
        
        $data['_view'] = 'item_table/index';
        $this->load->view('test',$data);
    }

    function index2()
    {
        $data['item_table'] = $this->Item_table_model->get_all_item_table();
        
        $data['_view'] = 'item_table/demo';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new item_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ITEM_UID' => $this->input->post('ITEM_UID'),
				'ITEM_SERIAL' => $this->input->post('ITEM_SERIAL'),
				'ITEM_NAME' => $this->input->post('ITEM_NAME'),
            );
            
            $item_table_id = $this->Item_table_model->add_item_table($params);
            redirect('item_table/index');
        }
        else
        {            
            $data['_view'] = 'item_table/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a item_table
     */
    function edit($ITEM_UID)
    {   
        // check if the item_table exists before trying to edit it
        $data['item_table'] = $this->Item_table_model->get_item_table($ITEM_UID);
        
        if(isset($data['item_table']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ITEM_UID' => $this->input->post('ITEM_UID'),
					'ITEM_SERIAL' => $this->input->post('ITEM_SERIAL'),
					'ITEM_NAME' => $this->input->post('ITEM_NAME'),
                );

                $this->Item_table_model->update_item_table($ITEM_UID,$params);            
                redirect('item_table/index');
            }
            else
            {
                $data['_view'] = 'item_table/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The item_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting item_table
     */
	
    function remove($ITEM_UID)
    {
        $item_table = $this->Item_table_model->get_item_table($ITEM_UID);

        // check if the item_table exists before trying to delete it
        if(isset($item_table['']))
        {
            $this->Item_table_model->delete_item_table($ITEM_UID);
            redirect('item_table/index');
        }
        else
            show_error('The item_table you are trying to delete does not exist.');
    }
    
}
