<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Refer extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Refer_model');
    } 

    /*
     * Listing of refer
     */
    function index()
    {
        $data['refer'] = $this->Refer_model->get_all_refer();
        
        $data['_view'] = 'refer/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new refer
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'REFERID' => $this->input->post('REFERID'),
				'DEPARTMENTID' => $this->input->post('DEPARTMENTID'),
				'REFERNAME' => $this->input->post('REFERNAME'),
            );
            
            $refer_id = $this->Refer_model->add_refer($params);
            redirect('refer/index');
        }
        else
        {
			$this->load->model('Department_model');
			$data['all_department'] = $this->Department_model->get_all_department();
            
            $data['_view'] = 'refer/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a refer
     */
    function edit($REFERID)
    {   
        // check if the refer exists before trying to edit it
        $data['refer'] = $this->Refer_model->get_refer($REFERID);
        
        if(isset($data['refer']['REFERID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'DEPARTMENTID' => $this->input->post('DEPARTMENTID'),
					'REFERNAME' => $this->input->post('REFERNAME'),
                );

                $this->Refer_model->update_refer($REFERID,$params);            
                redirect('refer/index');
            }
            else
            {
				$this->load->model('Department_model');
				$data['all_department'] = $this->Department_model->get_all_department();

                $data['_view'] = 'refer/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The refer you are trying to edit does not exist.');
    } 

    /*
     * Deleting refer
     */
    function remove($REFERID)
    {
        $refer = $this->Refer_model->get_refer($REFERID);

        // check if the refer exists before trying to delete it
        if(isset($refer['REFERID']))
        {
            $this->Refer_model->delete_refer($REFERID);
            redirect('refer/index');
        }
        else
            show_error('The refer you are trying to delete does not exist.');
    }
    
}
