<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Room_table_model');
    } 

    /*
     * Listing of room_table
     */
    function index()
    {
        $data['room_table'] = $this->Room_table_model->get_all_room_table();
        
        $data['_view'] = 'room_table/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new room_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'room_number' => $this->input->post('room_number'),
				'floor_rid' => $this->input->post('floor_rid'),
            );
            
            $room_table_id = $this->Room_table_model->add_room_table($params);
            redirect('room_table/index');
        }
        else
        {            
            $data['_view'] = 'room_table/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a room_table
     */
    function edit($room_rid)
    {   
        // check if the room_table exists before trying to edit it
        $data['room_table'] = $this->Room_table_model->get_room_table($room_rid);
        
        if(isset($data['room_table']['room_rid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'room_number' => $this->input->post('room_number'),
					'floor_rid' => $this->input->post('floor_rid'),
                );

                $this->Room_table_model->update_room_table($room_rid,$params);            
                redirect('room_table/index');
            }
            else
            {
                $data['_view'] = 'room_table/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The room_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting room_table
     */
    function remove($room_rid)
    {
        $room_table = $this->Room_table_model->get_room_table($ROroom_ridOM_RID);

        // check if the room_table exists before trying to delete it
        if(isset($room_table['room_rid']))
        {
            $this->Room_table_model->delete_room_table($room_rid);
            redirect('room_table/index');
        }
        else
            show_error('The room_table you are trying to delete does not exist.');
    }
    
}
