<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Room_model');
    } 

    /*
     * Listing of room
     */
    function index()
    {
        $data['room'] = $this->Room_model->get_all_room();
        
        $data['_view'] = 'room/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new room
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'FLOOR_RID' => $this->input->post('FLOOR_RID'),
				'DEPARTMENTID' => $this->input->post('DEPARTMENTID'),
				'ROOM_ID' => $this->input->post('ROOM_ID'),
            );
            
            $room_id = $this->Room_model->add_room($params);
            redirect('room/index');
        }
        else
        {
			$this->load->model('Floor_model');
			$data['all_floor'] = $this->Floor_model->get_all_floor();

			$this->load->model('Department_model');
			$data['all_department'] = $this->Department_model->get_all_department();
            
            $data['_view'] = 'room/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a room
     */
    function edit($ROOM_RID)
    {   
        // check if the room exists before trying to edit it
        $data['room'] = $this->Room_model->get_room($ROOM_RID);
        
        if(isset($data['room']['ROOM_RID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'FLOOR_RID' => $this->input->post('FLOOR_RID'),
					'DEPARTMENTID' => $this->input->post('DEPARTMENTID'),
					'ROOM_ID' => $this->input->post('ROOM_ID'),
                );

                $this->Room_model->update_room($ROOM_RID,$params);            
                redirect('room/index');
            }
            else
            {
				$this->load->model('Floor_model');
				$data['all_floor'] = $this->Floor_model->get_all_floor();

				$this->load->model('Department_model');
				$data['all_department'] = $this->Department_model->get_all_department();

                $data['_view'] = 'room/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The room you are trying to edit does not exist.');
    } 

    /*
     * Deleting room
     */
    function remove($ROOM_RID)
    {
        $room = $this->Room_model->get_room($ROOM_RID);

        // check if the room exists before trying to delete it
        if(isset($room['ROOM_RID']))
        {
            $this->Room_model->delete_room($ROOM_RID);
            redirect('room/index');
        }
        else
            show_error('The room you are trying to delete does not exist.');
    }
    
}
