<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Room_table_model');
    } 

    /*
     * Listing of room_table
     */
    function index()
    {
        $data['room_table'] = $this->Room_table_model->get_all_room_table();
        
        $data['_view'] = 'room_table/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new room_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'ROOM_NUMBER' => $this->input->post('ROOM_NUMBER'),
				'FLOOR_RID' => $this->input->post('FLOOR_RID'),
            );
            
            $room_table_id = $this->Room_table_model->add_room_table($params);
            redirect('room_table/index');
        }
        else
        {            
            $data['_view'] = 'room_table/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a room_table
     */
    function edit($ROOM_RID)
    {   
        // check if the room_table exists before trying to edit it
        $data['room_table'] = $this->Room_table_model->get_room_table($ROOM_RID);
        
        if(isset($data['room_table']['ROOM_RID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'ROOM_NUMBER' => $this->input->post('ROOM_NUMBER'),
					'FLOOR_RID' => $this->input->post('FLOOR_RID'),
                );

                $this->Room_table_model->update_room_table($ROOM_RID,$params);            
                redirect('room_table/index');
            }
            else
            {
                $data['_view'] = 'room_table/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The room_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting room_table
     */
    function remove($ROOM_RID)
    {
        $room_table = $this->Room_table_model->get_room_table($ROOM_RID);

        // check if the room_table exists before trying to delete it
        if(isset($room_table['ROOM_RID']))
        {
            $this->Room_table_model->delete_room_table($ROOM_RID);
            redirect('room_table/index');
        }
        else
            show_error('The room_table you are trying to delete does not exist.');
    }
    
}
