<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Search extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {
        $data['_view'] = 'search';
        $this->load->view('usermode',$data);
	}
	
	function index2()
    {
        $this->load->view('filter');
    }
}
