<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_model');
    } 

    /*
     * Listing of status
     */
    function index()
    {
        $data['status'] = $this->Status_model->get_all_status();
        
        $data['_view'] = 'status/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new status
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'STATUS_NAME' => $this->input->post('STATUS_NAME'),
            );
            
            $statu_id = $this->Status_model->add_status($params);
            redirect('status/index');
        }
        else
        {            
            $data['_view'] = 'status/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a status
     */
    function edit($STATUS_ID)
    {   
        // check if the status exists before trying to edit it
        $data['status'] = $this->Status_model->get_status($STATUS_ID);
        
        if(isset($data['status']['STATUS_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'STATUS_NAME' => $this->input->post('STATUS_NAME'),
                );

                $this->Status_model->update_status($STATUS_ID,$params);            
                redirect('status/index');
            }
            else
            {
                $data['_view'] = 'status/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The status you are trying to edit does not exist.');
    } 

    /*
     * Deleting status
     */
    function remove($STATUS_ID)
    {
        $status = $this->Status_model->get_status($STATUS_ID);

        // check if the status exists before trying to delete it
        if(isset($status['STATUS_ID']))
        {
            $this->Status_model->delete_status($STATUS_ID);
            redirect('status/index');
        }
        else
            show_error('The status you are trying to delete does not exist.');
    }
    
}
