<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_table extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Status_table_model');
    } 

    /*
     * Listing of status_table
     */
    function index()
    {
        $data['status_table'] = $this->Status_table_model->get_all_status_table();
        
        $data['_view'] = 'status_table/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new status_table
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status_name' => $this->input->post('status_name'),
            );
            
            $status_table_id = $this->Status_table_model->add_status_table($params);
            redirect('status_table/index');
        }
        else
        {            
            $data['_view'] = 'status_table/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a status_table
     */
    function edit($status_rid)
    {   
        // check if the status_table exists before trying to edit it
        $data['status_table'] = $this->Status_table_model->get_status_table($status_rid);
        
        if(isset($data['status_table']['status_rid']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status_name' => $this->input->post('status_name'),
                );

                $this->Status_table_model->update_status_table($status_rid,$params);            
                redirect('status_table/index');
            }
            else
            {
                $data['_view'] = 'status_table/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The status_table you are trying to edit does not exist.');
    } 

    /*
     * Deleting status_table
     */
    function remove($status_rid)
    {
        $status_table = $this->Status_table_model->get_status_table($status_rid);

        // check if the status_table exists before trying to delete it
        if(isset($status_table['status_rid']))
        {
            $this->Status_table_model->delete_status_table($status_rid);
            redirect('status_table/index');
        }
        else
            show_error('The status_table you are trying to delete does not exist.');
    }
    
}
