<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of user
     */
    function index()
    {
        $data['user'] = $this->User_model->get_all_user();
        
        $data['_view'] = 'user/index';
        $this->load->view('test',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'REFERID' => $this->input->post('REFERID'),
				'USER_USERNAME' => $this->input->post('USER_USERNAME'),
				'USER_PASSWORD' => hash('sha512',$this->input->post('USER_PASSWORD')),
				'AUTH' => $this->input->post('AUTH'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
			$this->load->model('Refer_model');
			$data['all_refer'] = $this->Refer_model->get_all_refer();
            
            $data['_view'] = 'user/add';
            $this->load->view('test',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($USER_ID)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($USER_ID);
        
        if(isset($data['user']['USER_ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'REFERID' => $this->input->post('REFERID'),
					'USER_USERNAME' => $this->input->post('USER_USERNAME'),
					'USER_PASSWORD' => hash('sha512',$this->input->post('USER_PASSWORD')),
					'AUTH' => $this->input->post('AUTH'),
                );

                $this->User_model->update_user($USER_ID,$params);            
                redirect('user/index');
            }
            else
            {
				$this->load->model('Refer_model');
				$data['all_refer'] = $this->Refer_model->get_all_refer();

                $data['_view'] = 'user/edit';
                $this->load->view('test',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($USER_ID)
    {
        $user = $this->User_model->get_user($USER_ID);

        // check if the user exists before trying to delete it
        if(isset($user['USER_ID']))
        {
            $this->User_model->delete_user($USER_ID);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
