<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_item_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_item by id
     */
    function get_tb_item($id)
    {
        return $this->db->get_where('tb_item',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tb_item
     */
    function get_all_tb_item()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tb_item')->result_array();
    }
        
    /*
     * function to add new tb_item
     */
    function add_tb_item($params)
    {
        $this->db->insert('tb_item',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_item
     */
    function update_tb_item($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_item',$params);
    }
    
    /*
     * function to delete tb_item
     */
    function delete_tb_item($id)
    {
        return $this->db->delete('tb_item',array('id'=>$id));
    }
}
