<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asset_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asset by ASSETID
     */
    function get_asset($ASSETID)
    {
        return $this->db->get_where('ASSET',array('ASSETID'=>$ASSETID))->row_array();
    }
    
    /*
     * Get all asset count
     */
    function get_all_asset_count()
    {
        $this->db->from('ASSET');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all asset
     */
    function get_all_asset($params = array())
    {
        $this->db->order_by('ASSETID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('ASSET')->result_array();
    }
        
    /*
     * function to add new asset
     */
    function add_asset($params)
    {
        $this->db->insert('ASSET',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asset
     */
    function update_asset($ASSETID,$params)
    {
        $this->db->where('ASSETID',$ASSETID);
        return $this->db->update('ASSET',$params);
    }
    
    /*
     * function to delete asset
     */
    function delete_asset($ASSETID)
    {
        return $this->db->delete('ASSET',array('ASSETID'=>$ASSETID));
    }
}
