<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Building_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get building by BUILDING_ID
     */
    function get_building($BUILDING_ID)
    {
        return $this->db->get_where('BUILDING',array('BUILDING_ID'=>$BUILDING_ID))->row_array();
    }
        
    /*
     * Get all building
     */
    function get_all_building()
    {
        $this->db->order_by('BUILDING_ID', 'desc');
        return $this->db->get('BUILDING')->result_array();
    }
        
    /*
     * function to add new building
     */
    function add_building($params)
    {
        $this->db->insert('BUILDING',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update building
     */
    function update_building($BUILDING_ID,$params)
    {
        $this->db->where('BUILDING_ID',$BUILDING_ID);
        return $this->db->update('BUILDING',$params);
    }
    
    /*
     * function to delete building
     */
    function delete_building($BUILDING_ID)
    {
        return $this->db->delete('BUILDING',array('BUILDING_ID'=>$BUILDING_ID));
    }
}
