<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Building_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get building_table by BUILDING_RID
     */
    function get_building_table($BUILDING_RID)
    {
        return $this->db->get_where('building_table',array('BUILDING_RID'=>$BUILDING_RID))->row_array();
    }
        
    /*
     * Get all building_table
     */
    function get_all_building_table()
    {
        $this->db->order_by('BUILDING_RID', 'desc');
        return $this->db->get('building_table')->result_array();
    }
        
    /*
     * function to add new building_table
     */
    function add_building_table($params)
    {
        $this->db->insert('building_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update building_table
     */
    function update_building_table($BUILDING_RID,$params)
    {
        $this->db->where('BUILDING_RID',$BUILDING_RID);
        return $this->db->update('building_table',$params);
    }
    
    /*
     * function to delete building_table
     */
    function delete_building_table($BUILDING_RID)
    {
        return $this->db->delete('building_table',array('BUILDING_RID'=>$BUILDING_RID));
    }
}
