<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Building_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get building_table by BUILDING_RID
     */
    function get_building_table($building_rid)
    {
        return $this->db->get_where('BUILDING_TABLE',array('building_rid'=>$building_rid))->row_array();
    }
        
    /*
     * Get all building_table
     */
    function get_all_building_table()
    {
        $this->db->order_by('building_rid', 'desc');
        return $this->db->get('BUILDING_TABLE')->result_array();
    }
        
    /*
     * function to add new building_table
     */
    function add_building_table($params)
    {
        $this->db->insert('BUILDING_TABLE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update building_table
     */
    function update_building_table($building_rid,$params)
    {
        $this->db->where('building_rid',$building_rid);
        return $this->db->update('BUILDING_TABLE',$params);
    }
    
    /*
     * function to delete building_table
     */
    function delete_building_table($building_rid)
    {
        return $this->db->delete('BUILDING_TABLE',array('building_rid'=>$building_rid));
    }
}
