<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Floor_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get floor_table by FLOOR_RID
     */
    function get_floor_table($floor_rid)
    {
        return $this->db->get_where('FLOOR_TABLE',array('floor_rid'=>$floor_rid))->row_array();
    }
        
    /*
     * Get all floor_table
     */
    function get_all_floor_table()
    {
        $this->db->order_by('floor_rid', 'desc');
        return $this->db->get('FLOOR_TABLE')->result_array();
    }
        
    /*
     * function to add new floor_table
     */
    function add_floor_table($params)
    {
        $this->db->insert('FLOOR_TABLE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update floor_table
     */
    function update_floor_table($floor_rid,$params)
    {
        $this->db->where('floor_rid',$floor_rid);
        return $this->db->update('FLOOR_TABLE',$params);
    }
    
    /*
     * function to delete floor_table
     */
    function delete_floor_table($floor_rid)
    {
        return $this->db->delete('FLOOR_TABLE',array('floor_rid'=>$floor_rid));
    }
}
