<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Floor_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get floor_table by FLOOR_RID
     */
    function get_floor_table($FLOOR_RID)
    {
        return $this->db->get_where('floor_table',array('FLOOR_RID'=>$FLOOR_RID))->row_array();
    }
        
    /*
     * Get all floor_table
     */
    function get_all_floor_table()
    {
        $this->db->order_by('FLOOR_RID', 'desc');
        return $this->db->get('floor_table')->result_array();
    }
        
    /*
     * function to add new floor_table
     */
    function add_floor_table($params)
    {
        $this->db->insert('floor_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update floor_table
     */
    function update_floor_table($FLOOR_RID,$params)
    {
        $this->db->where('FLOOR_RID',$FLOOR_RID);
        return $this->db->update('floor_table',$params);
    }
    
    /*
     * function to delete floor_table
     */
    function delete_floor_table($FLOOR_RID)
    {
        return $this->db->delete('floor_table',array('FLOOR_RID'=>$FLOOR_RID));
    }
}
