<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class History_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get history_table by HISTORY_RID
     */
    function get_history_table($HISTORY_RID)
    {
        return $this->db->get_where('history_table',array('HISTORY_RID'=>$HISTORY_RID))->row_array();
    }
        
    /*
     * Get all history_table
     */
    function get_all_history_table()
    {
        $this->db->order_by('HISTORY_RID', 'desc');
        return $this->db->get('history_table')->result_array();
    }
        
    /*
     * function to add new history_table
     */
    function add_history_table($params)
    {
        $this->db->insert('history_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update history_table
     */
    function update_history_table($HISTORY_RID,$params)
    {
        $this->db->where('HISTORY_RID',$HISTORY_RID);
        return $this->db->update('history_table',$params);
    }
    
    /*
     * function to delete history_table
     */
    function delete_history_table($HISTORY_RID)
    {
        return $this->db->delete('history_table',array('HISTORY_RID'=>$HISTORY_RID));
    }
}
