<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class History_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get history_table by HISTORY_RID
     */
    function get_history_table($history_rid)
    {
        return $this->db->get_where('HISTORY_TABLE',array('history_rid'=>$history_rid))->row_array();
    }
        
    /*
     * Get all history_table
     */
    function get_all_history_table()
    {
        $this->db->order_by('history_rid', 'desc');
        return $this->db->get('HISTORY_TABLE')->result_array();
    }
        
    /*
     * function to add new history_table
     */
    function add_history_table($params)
    {
        $this->db->insert('HISTORY_TABLE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update history_table
     */
    function update_history_table($history_rid,$params)
    {
        $this->db->where('history_rid',$history_rid);
        return $this->db->update('HISTORY_TABLE',$params);
    }
    
    /*
     * function to delete history_table
     */
    function delete_history_table($history_rid)
    {
        return $this->db->delete('HISTORY_TABLE',array('history_rid'=>$history_rid));
    }
}
