<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class History_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get history by HISTORY_RID
     */
    function get_history($HISTORY_RID)
    {
        return $this->db->get_where('HISTORY_ASSET',array('HISTORY_RID'=>$HISTORY_RID))->row_array();
    }
        
    /*
     * Get all history
     */
    function get_all_history()
    {
        $this->db->order_by('HISTORY_RID', 'desc');
        return $this->db->get('HISTORY_ASSET')->result_array();
    }
        
    /*
     * function to add new history
     */
    function add_history($params)
    {
        $this->db->insert('HISTORY_ASSET',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update history
     */
    function update_history($HISTORY_RID,$params)
    {
        $this->db->where('HISTORY_RID',$HISTORY_RID);
        return $this->db->update('HISTORY_ASSET',$params);
    }
    
    /*
     * function to delete history
     */
    function delete_history($HISTORY_RID)
    {
        return $this->db->delete('HISTORY_ASSET',array('HISTORY_RID'=>$HISTORY_RID));
    }
}
