<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get item_table by ITEM_ID
     */
    function get_item_table($ITEM_ID)
    {
        return $this->db->get_where('item_table',array('ITEM_ID'=>$ITEM_ID))->row_array();
    }
        
    /*
     * Get all item_table
     */
    function get_all_item_table()
    {
        $this->db->order_by('ITEM_ID', 'desc');
        return $this->db->get('item_table')->result_array();
    }
        
    /*
     * function to add new item_table
     */
    function add_item_table($params)
    {
        $this->db->insert('item_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update item_table
     */
    function update_item_table($ITEM_ID,$params)
    {
        $this->db->where('ITEM_ID',$ITEM_ID);
        return $this->db->update('item_table',$params);
    }
    
    /*
     * function to delete item_table
     */
    function delete_item_table($ITEM_ID)
    {
        return $this->db->delete('item_table',array('ITEM_ID'=>$ITEM_ID));
    }
}