<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Location_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get location by LOCATION_ID
     */
    function get_location($LOCATION_ID)
    {
        return $this->db->get_where('LOCATION',array('LOCATION_ID'=>$LOCATION_ID))->row_array();
    }
        
    /*
     * Get all location
     */
    function get_all_location()
    {
        $this->db->order_by('LOCATION_ID', 'desc');
        return $this->db->get('LOCATION')->result_array();
    }
        
    /*
     * function to add new location
     */
    function add_location($params)
    {
        $this->db->insert('LOCATION',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update location
     */
    function update_location($LOCATION_ID,$params)
    {
        $this->db->where('LOCATION_ID',$LOCATION_ID);
        return $this->db->update('LOCATION',$params);
    }
    
    /*
     * function to delete location
     */
    function delete_location($LOCATION_ID)
    {
        return $this->db->delete('LOCATION',array('LOCATION_ID'=>$LOCATION_ID));
    }
}
