<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Map_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get map_table by MAP_RID
     */
    function get_map_table($map_rid)
    {
        return $this->db->get_where('MAP_TABLE',array('map_rid'=>$map_rid))->row_array();
    }
        
    /*
     * Get all map_table
     */
    function get_all_map_table()
    {
        $this->db->order_by('map_rid', 'desc');
        return $this->db->get('MAP_TABLE')->result_array();
    }
        
    /*
     * function to add new map_table
     */
    function add_map_table($params)
    {
        $this->db->insert('MAP_TABLE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update map_table
     */
    function update_map_table($map_rid,$params)
    {
        $this->db->where('map_rid',$map_rid);
        return $this->db->update('MAP_TABLE',$params);
    }
    
    /*
     * function to delete map_table
     */
    function delete_map_table($map_rid)
    {
        return $this->db->delete('MAP_TABLE',array('map_rid'=>$map_rid));
    }
}
