<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Map_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get map_table by MAP_RID
     */
    function get_map_table($MAP_RID)
    {
        return $this->db->get_where('map_table',array('MAP_RID'=>$MAP_RID))->row_array();
    }
        
    /*
     * Get all map_table
     */
    function get_all_map_table()
    {
        $this->db->order_by('MAP_RID', 'desc');
        return $this->db->get('map_table')->result_array();
    }
        
    /*
     * function to add new map_table
     */
    function add_map_table($params)
    {
        $this->db->insert('map_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update map_table
     */
    function update_map_table($MAP_RID,$params)
    {
        $this->db->where('MAP_RID',$MAP_RID);
        return $this->db->update('map_table',$params);
    }
    
    /*
     * function to delete map_table
     */
    function delete_map_table($MAP_RID)
    {
        return $this->db->delete('map_table',array('MAP_RID'=>$MAP_RID));
    }
}
