<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Owner_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get owner_table by 
     */
    function get_owner_table($OWNER_UID)
    {
        return $this->db->get_where('owner_table',array(''=>$OWNER_UID))->row_array();
    }
        
    /*
     * Get all owner_table
     */
    function get_all_owner_table()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('owner_table')->result_array();
    }
        
    /*
     * function to add new owner_table
     */
    function add_owner_table($params)
    {
        $this->db->insert('owner_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update owner_table
     */
    function update_owner_table($OWNER_UID,$params)
    {
        $this->db->where('',$OWNER_UID);
        return $this->db->update('owner_table',$params);
    }
    
    /*
     * function to delete owner_table
     */
    function delete_owner_table($OWNER_UID)
    {
        return $this->db->delete('owner_table',array(''=>$OWNER_UID));
    }
}
