<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get room_table by ROOM_RID
     */
    function get_room_table($room_rid)
    {
        return $this->db->get_where('ROOM_TABLE-',array('room_rid'=>$room_rid))->row_array();
    }
        
    /*
     * Get all room_table
     */
    function get_all_room_table()
    {
        $this->db->order_by('room_rid', 'desc');
        return $this->db->get('ROOM_TABLE')->result_array();
    }
        
    /*
     * function to add new room_table
     */
    function add_room_table($params)
    {
        $this->db->insert('ROOM_TABLE',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update room_table
     */
    function update_room_table($room_rid,$params)
    {
        $this->db->where('room_rid',$room_rid);
        return $this->db->update('room_table',$params);
    }
    
    /*
     * function to delete room_table
     */
    function delete_room_table($room_rid)
    {
        return $this->db->delete('ROOM_TABLE',array('room_rid'=>$room_rid));
    }
}
