<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_table_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get room_table by ROOM_RID
     */
    function get_room_table($ROOM_RID)
    {
        return $this->db->get_where('room_table',array('ROOM_RID'=>$ROOM_RID))->row_array();
    }
        
    /*
     * Get all room_table
     */
    function get_all_room_table()
    {
        $this->db->order_by('ROOM_RID', 'desc');
        return $this->db->get('room_table')->result_array();
    }
        
    /*
     * function to add new room_table
     */
    function add_room_table($params)
    {
        $this->db->insert('room_table',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update room_table
     */
    function update_room_table($ROOM_RID,$params)
    {
        $this->db->where('ROOM_RID',$ROOM_RID);
        return $this->db->update('room_table',$params);
    }
    
    /*
     * function to delete room_table
     */
    function delete_room_table($ROOM_RID)
    {
        return $this->db->delete('room_table',array('ROOM_RID'=>$ROOM_RID));
    }
}
