<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Room_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get room by ROOM_RID
     */
    function get_room($ROOM_RID)
    {
        return $this->db->get_where('ROOM',array('ROOM_RID'=>$ROOM_RID))->row_array();
    }
        
    /*
     * Get all room
     */
    function get_all_room()
    {
        $this->db->order_by('ROOM_RID', 'desc');
        return $this->db->get('ROOM')->result_array();
    }
        
    /*
     * function to add new room
     */
    function add_room($params)
    {
        $this->db->insert('ROOM',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update room
     */
    function update_room($ROOM_RID,$params)
    {
        $this->db->where('ROOM_RID',$ROOM_RID);
        return $this->db->update('ROOM',$params);
    }
    
    /*
     * function to delete room
     */
    function delete_room($ROOM_RID)
    {
        return $this->db->delete('ROOM',array('ROOM_RID'=>$ROOM_RID));
    }
}
