<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Statu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get statu by STATUS_ID
     */
    function get_statu($STATUS_ID)
    {
        return $this->db->get_where('STATUS',array('STATUS_ID'=>$STATUS_ID))->row_array();
    }
        
    /*
     * Get all status
     */
    function get_all_status()
    {
        $this->db->order_by('STATUS_ID', 'desc');
        return $this->db->get('STATUS')->result_array();
    }
        
    /*
     * function to add new statu
     */
    function add_statu($params)
    {
        $this->db->insert('STATUS',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update statu
     */
    function update_statu($STATUS_ID,$params)
    {
        $this->db->where('STATUS_ID',$STATUS_ID);
        return $this->db->update('STATUS',$params);
    }
    
    /*
     * function to delete statu
     */
    function delete_statu($STATUS_ID)
    {
        return $this->db->delete('STATUS',array('STATUS_ID'=>$STATUS_ID));
    }
}
