<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by USER_ID
     */
    function get_user($USER_ID)
    {
        return $this->db->get_where('USER',array('USER_ID'=>$USER_ID))->row_array();
    }
        
    /*
     * Get all user
     */
    function get_all_user()
    {
        $this->db->order_by('USER_ID', 'desc');
        return $this->db->get('USER')->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('USER',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($USER_ID,$params)
    {
        $this->db->where('USER_ID',$USER_ID);
        return $this->db->update('USER',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($USER_ID)
    {
        return $this->db->delete('USER',array('USER_ID'=>$USER_ID));
    }
}
